#pragma once

#define DRIVE_SPEED_CONTROLLER_FL_CHANNEL 1
#define DRIVE_SPEED_CONTROLLER_FR_CHANNEL 3
#define DRIVE_SPEED_CONTROLLER_BL_CHANNEL 0
#define DRIVE_SPEED_CONTROLLER_BR_CHANNEL 2

#define GYRO_ANALOG_PORT 0

#define PCM_PORT 0 //Pnuematics Control Module
#define DOUBLESOLENOID_FORWARD_CHANNEL 4
#define DOUBLESOLENOID_REVERSE_CHANNEL 5
