#pragma once

// CAN IDs
#define DRIVE_SPEED_CONTROLLER_FL_CHANNEL 1
#define DRIVE_SPEED_CONTROLLER_FR_CHANNEL 3
#define DRIVE_SPEED_CONTROLLER_BL_CHANNEL 0
#define DRIVE_SPEED_CONTROLLER_BR_CHANNEL 2

#define COLOR_WHEEL_SPEED_CONTROLLER 5

#define BALL_INTAKE_FLIPPER_SPEED_CONTROLLER 6
#define BALL_INTAKE_UPPER_SPEED_CONTROLLER 7

#define LIFT_ARM_SPEED_CONTROLLER 8
#define WINCH_TELESCOPE_SPEED_CONTROLLER 9
#define WINCH_PULLUP_SPEED_CONTROLLER 10


// PWM IDs
#define BALL_INTAKE_LOWER_SPEED_CONTROLLER 0

#define GYRO_ANALOG_PORT 0

#define PCM_PORT 0 //Pnuematics Control Module
#define DOUBLESOLENOID_FORWARD_CHANNEL 4
#define DOUBLESOLENOID_REVERSE_CHANNEL 5

// DIO Channels
#define FLIPPER_ENCODER_CHANNEL_A 0
#define FLIPPER_ENCODER_CHANNEL_B 1

#define LIFT_ARM_ENCODER_CHANNEL_A 2
#define LIFT_ARM_ENCODER_CHANNEL_B 3
